### ISSUE TITLE
Scoreboard api issue

### ISSUE THREAD

**Issue by BlackKnight683** [lt-name/BlockHunt#5]
Sorry For Being Annoying, but now i saw the error and it says scoreboard api not found, whereas your other 2 plugins (murdermystery and gunwar) have no issue in finding the scoreboard api.... can u please help me?

chinese translation (via google):

对不起，很烦人，但现在我看到了错误，并说没有找到记分板api，而您的其他2个插件（谋杀案和枪战）在找到记分板api方面没有问题....您能帮我吗？

![IMG_20200825_092527](https://user-images.githubusercontent.com/69863661/91121221-f78df980-e6b4-11ea-92bc-d5e295c37825.jpg)
![IMG_20200825_092502](https://user-images.githubusercontent.com/69863661/91121227-f8bf2680-e6b4-11ea-8b9b-2012ba608300.jpg)

**Comment by lt-name** [comment]
I think this may be a problem with the order of enabling plugins

**Comment by BlackKnight683** [comment]
how can i fix it? 😬😬

**Comment by lt-name** [comment]
Maybe you can rename the scoreboard to "a"
Let nukkit read the scoreboard first

**Comment by BlackKnight683** [comment]
oo oki, lemme try

**Comment by BlackKnight683** [comment]
it worked! tysm :D

**Comment by lt-name** [comment]
If you encounter problems, you can also contact me through discord
https://discord.gg/pJjQDQC
